### ISSUE TITLE
Build failed when adding custom remark/rehype plugin

### ISSUE THREAD

**Issue by thenasim** [kentcdodds/mdx-bundler#93] opened 2021-09-10 05:25 UTC
- `mdx-bundler` version: 6.0.1
- `node` version: 14.17.0
- `npm` version: 6.14.13
- `esbuild` version: 0.12.25
- `platform`: windows 11

Relevant code or config
```ts
async function getFileRenderBySlug(type: string, slug: string) {
  const file_path = path.join(BLOG_FOLDER_PATH, type, `${slug}.mdx`);

  if (checkIfPathExists(file_path) === false) {
    throw new Error(`${file_path} file not found`);
  }

  const mdxSource = fs.readFileSync(file_path, "utf8");

  if (process.platform === "win32") {
    process.env.ESBUILD_BINARY_PATH = path.join(
      ROOT,
      "node_modules",
      "esbuild",
      "esbuild.exe"
    );
  } else {
    process.env.ESBUILD_BINARY_PATH = path.join(
      ROOT,
      "node_modules",
      "esbuild",
      "bin",
      "esbuild"
    );
  }

  const result = await bundleMDX(mdxSource, {
    cwd: path.join(ROOT, COMPONENTS),
    xdmOptions(options) {
      options.remarkPlugins = [
        ...(options.remarkPlugins ?? []),
        // if I remove this plugins it builds without any issue
        remarkGfm,
        remarkToc,
        remarkMath,
      ];
      options.rehypePlugins = [
        ...(options.rehypePlugins ?? []),
        // if I remove this plugins it builds without any issue
        rehypePrism,
        rehypeKatex,
      ];

      return options;
    },
  });

  const { code, frontmatter } = result;

  return {
    toRender: code,
    data: {
      readingTime: readingTime(code),
      ...(frontmatter as MarkdownFrontMatter),
    },
  };
}
```

Error Output:
```
Server Error
Error: Build failed with 1 error:
_mdx_bundler_entry_point-1f92ed01-7bb4-4697-9847-570c4c57cf02.mdx:0:0: error: [plugin: esbuild-xdm] 

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Call Stack
failureErrorWithLog
file:///E:/projects/next-ts-blog-starter/node_modules/esbuild/lib/main.js (1478:15)
<unknown>
file:///E:/projects/next-ts-blog-starter/node_modules/esbuild/lib/main.js (1136:28)
runOnEndCallbacks
file:///E:/projects/next-ts-blog-starter/node_modules/esbuild/lib/main.js (926:63)
buildResponseToResult
file:///E:/projects/next-ts-blog-starter/node_modules/esbuild/lib/main.js (1134:7)
<unknown>
file:///E:/projects/next-ts-blog-starter/node_modules/esbuild/lib/main.js (1243:14)
<unknown>
file:///E:/projects/next-ts-blog-starter/node_modules/esbuild/lib/main.js (614:9)
handleIncomingPacket
file:///E:/projects/next-ts-blog-starter/node_modules/esbuild/lib/main.js (711:9)
Socket.readFromStdout
file:///E:/projects/next-ts-blog-starter/node_modules/esbuild/lib/main.js (581:7)
Socket.emit
events.js (376:20)
Socket.emit
domain.js (470:12)
```

When I am adding my custom remark/rehype plugins, it fails to build. But if I remove all my custom remark/rehype plugins it builds without any issue. Don't know where I am doing wrong.
Currently moved to `next-mdx-remote` 😅

**Comment by Utkarshbhimte** [comment] 2021-09-10 14:18
I am facing the same isssue

**Comment by Arcath** [comment] 2021-09-12 14:16
Does it fail with just one plugin? I have a few plugins both remark and rehype on my site with no issues so I'd guess its a specific plugin thats causing issues.

**Comment by chasemccoy** [comment] 2021-09-12 21:13
I'm having this issue as well. All of the remark plugins that I have installed from npm and import work just fine, but the two remark plugins that I have written myself cause this failure. 

Here's my relevant code:

```js
const imageTransformer = (tree) => {
  visit(tree, 'image', (node, index, parent) => {
    const filename = String(node.url)
    node.url = `/img/${slug}/${filename}`

    if (node.title) {
      parent.type = 'div'
    }
  })

  return tree
}

const getToC = (tree) => {
  const mdast = toc(tree)
  if (mdast.map) {
    tocData = toHtml(toHast(mdast.map))
  }
}

const remarkPlugins = [
  gfm,
  smartypants,
  () => imageTransformer,
  () => getToC,
  remarkSlug,
]
```

I have noticed that if I comment out the parts of my plugins that use imported modules (like `visit`, `toHast`, etc.) it works again. Perhaps these imported modules are not in scope in the context that the plugin is running? Not sure.

**Comment by wooorm** [comment] 2021-09-17 16:51
@chasemccoy Are you getting the *exact* same error?

The plugin looks wonky: where is `tocData` used? what is `parent.type = 'div'` supposed to do? 🤔

**Comment by chasemccoy** [comment] 2021-09-17 17:28
@wooorm Attaching the actual error I get here. Also I am definitely doing wonky things here, but worth noting that I can remove all of my own code from these plugins and they still error as long as I'm calling an imported function within them (like `visit`, `toHast`, etc.)

```
[1]  > _mdx_bundler_entry_point-56dc6681-facc-404c-a959-af8a4ea0239b.mdx:0:0: error: [plugin: esbuild-xdm] 
[1]     0 │ ---
[1]       ╵ ^
[1] 
[1] Error: Build failed with 1 error:
[1] _mdx_bundler_entry_point-56dc6681-facc-404c-a959-af8a4ea0239b.mdx:0:0: error: [plugin: esbuild-xdm] 
[1]     at failureErrorWithLog (/Users/chsmc/stripe/www/node_modules/esbuild/lib/main.js:1478:15)
[1]     at /Users/chsmc/stripe/www/node_modules/esbuild/lib/main.js:1136:28
[1]     at runOnEndCallbacks (/Users/chsmc/stripe/www/node_modules/esbuild/lib/main.js:926:63)
[1]     at buildResponseToResult (/Users/chsmc/stripe/www/node_modules/esbuild/lib/main.js:1134:7)
[1]     at /Users/chsmc/stripe/www/node_modules/esbuild/lib/main.js:1243:14
[1]     at /Users/chsmc/stripe/www/node_modules/esbuild/lib/main.js:614:9
[1]     at handleIncomingPacket (/Users/chsmc/stripe/www/node_modules/esbuild/lib/main.js:711:9)
[1]     at Socket.readFromStdout (/Users/chsmc/stripe/www/node_modules/esbuild/lib/main.js:581:7)
[1]     at Socket.emit (events.js:315:20)
[1]     at addChunk (_stream_readable.js:309:12) {
[1]   errors: [
[1]     {
[1]       detail: [TypeError],
[1]       location: [Object],
[1]       notes: [],
[1]       pluginName: 'esbuild-xdm',
[1]       text: ''
[1]     }
[1]   ],
[1]   warnings: []
[1] }
```

**Comment by chasemccoy** [comment] 2021-09-17 17:30
@wooorm  I later transform my images with titles into `figure` and `figcaption` so changing the parent type in my plugin makes sure that my `figure`s aren't nested in paragraph tags (which is invalid HTML). But again, commenting out all of that still throws this error as long as I'm calling an imported module in my plugin.

**Comment by wooorm** [comment] 2021-09-18 08:02
@chasemccoy I’m not getting any error when trying your code out. I installed the projects you use, wrapped your sample code into a full example that uses mdx-bundler, and defined the `tocData` variable:

```js
import {bundleMDX} from 'mdx-bundler'
import gfm from 'remark-gfm'
import remarkSlug from 'remark-slug'
import smartypants from '@silvenon/remark-smartypants'
import {visit} from 'unist-util-visit'
import {toc} from 'mdast-util-toc'
import {toHast} from 'mdast-util-to-hast'
import {toHtml} from 'hast-util-to-html'

const mdxSource = `
# Wahoo

Here's a **neat** demo.
`.trim()


let tocData

const imageTransformer = (tree) => {
  visit(tree, 'image', (node, index, parent) => {
    const filename = String(node.url)
    // To do: where are `slug` coming from?
    node.url = `/img/${slug}/${filename}`

    if (node.title) {
      parent.type = 'div'
    }
  })

  return tree
}

const getToC = (tree) => {
  const mdast = toc(tree)
  if (mdast.map) {
    tocData = toHtml(toHast(mdast.map))
  }
}

const remarkPlugins = [
  gfm,
  smartypants,
  remarkSlug,
  // Commenting out the next two plugins resolves the build failure
  () => imageTransformer,
  () => getToC,
]

const result = await bundleMDX(mdxSource, {xdmOptions() {
  return {remarkPlugins}
}})

const {code, frontmatter} = result

console.log(code);
```

Note that `unist-util-visit`, `mdast-util-toc`, `mdast-util-to-hast`, and `hast-util-to-html` are packages available on npm which have to be imported to be used.

---

Regarding the figure/figcaption from an image, I recommend to do it in the rehype ecosystem instead. rehype is an AST for HTML, and HTML knows about `img`, `p`, `div`, `figure`, and `figcaption`. Markdown (remark) has no knowledge of divs, figures, and figcaptions. Something along these lines?

```js
import {visit} from 'unist-util-visit'

function rehypeRewriteImageUrlsAndMakeThemFigures() {
  return (tree) => {
    visit(tree, (node, _, parent) => {
      if (node.type === 'element' && node.tagName === 'img') {
        const props = node.properties || (node.properties = {})

        try {
          // Resolve from a certain url
          props.src = (new URL(props.src, 'https://example.com/path/to/img/')).pathname
        } catch { /* Invalid src? Maybe warn? */ }

        if (
          parent &&
          parent.type === 'element' &&
          parent.tagName === 'p' &&
          // If this `img` is the only child of the `p`:
          parent.children.length === 1
        ) {
          // Change the tag name of the parent `p`.
          parent.tagName === 'figure'

          // Add a caption if there’s a title.
          if (props.title) {
            props.title = undefined
            parent.children.push({
              type: 'element',
              tagName: 'figcaption',
              properties: {},
              children: [{type: 'text', value: props.title}]
            })
          }
        }
      }
    })
  }
}
```

**Comment by Utkarshbhimte** [comment] 2021-09-18 08:05
@wooorm Can you add some metadata to that `mdxSource`. 

```
---
title: Some random string
---
```

**Comment by wooorm** [comment] 2021-09-18 08:16
Adding frontmatter does not result in an error in this first example of https://github.com/kentcdodds/mdx-bundler/issues/93#issuecomment-922237007.

@Utkarshbhimte @thenasim can you provide which plugins you are using that failed?

**Comment by Utkarshbhimte** [comment] 2021-09-18 08:19
@wooorm I am using https://github.com/landakram/remark-wiki-link and it only causes this error when I added extra arguments, if I don't add the second element in the array it builds fine.

```js
const { code, frontmatter } = await bundleMDX(source, {
    xdmOptions(options) {
      options.remarkPlugins = [
        ...(options?.remarkPlugins ?? []),
        remarkGfm,
        [
          wikiLinkPlugin,
          {
            hrefTemplate: permalink => permalink && `/blog/${permalink}` || '',
            pageResolver: (name) => name?.replaceAll(' ', '-')?.toLowerCase()
          }
        ]
      ];
      options.rehypePlugins = [
        ...(options?.rehypePlugins ?? []),
        rehypeSlug,
        rehypeCodeTitles,
        rehypePrism,
        [
          rehypeAutolinkHeadings,
          {
            properties: {
              className: ['anchor']
            }
          }
        ]
      ];
      return options;
    }
  });```

**Comment by wooorm** [comment] 2021-09-18 08:33
I can’t reproduce your problem. This works fine:

```js
import {bundleMDX} from 'mdx-bundler'
import remarkGfm from 'remark-gfm'
import rehypeSlug from 'rehype-slug'
import rehypeCodeTitles from 'rehype-code-titles'
import remarkWikiLink from 'remark-wiki-link'
import rehypePrism from '@mapbox/rehype-prism'
import rehypeAutolinkHeadings from 'rehype-autolink-headings'

const { code, frontmatter } = await bundleMDX(`---
title: a
---

# hello!`, {
  xdmOptions(options) {
    return {
      ...options,
      remarkPlugins: [
        remarkGfm,
        [
          remarkWikiLink,
          {
            hrefTemplate: permalink => permalink && `/blog/${permalink}` || '',
            pageResolver: (name) => name?.replaceAll(' ', '-')?.toLowerCase()
          }
        ]
      ],
      rehypePlugins: [
        rehypeSlug,
        rehypeCodeTitles,
        rehypePrism,
        [rehypeAutolinkHeadings, {properties: {className: ['anchor']}}]
      ]
    }
    return options;
  }
});

console.log(code);
```

**Comment by Utkarshbhimte** [comment] 2021-09-18 08:35
Interesting, can you also share your package.json as well?

**Comment by wooorm** [comment] 2021-09-18 08:40
This is in Node.js using actual ESM. That implies that the problem is either next.js or the input you are passing to mdx-bundler.
The dependencies are all just installed: latest everything.

**Comment by thenasim** [comment] 2021-09-18 09:37
@wooorm @Arcath I have solved my issue. I am using `rehype-code-titles` and In the mdx file I have used something like this.

\```js:hello.ts
    console.log('hello');
\```

But I forgot to add the `rehype-code-titles` in the plugin list. Silly mistake 😔
That caused the whole build failed. Now it's working without any issue.

**Comment by thenasim** [comment] 2021-09-18 10:29
Another very important thing, the plugin order matters. I have used `rehype-code-titles` and `rehype-prism-plus`. 
First I have to use `rehype-code-titles` and then `rehype-prism-plug`

For example, It fails to build
```js
options.rehypePlugins = [
        ...(options.rehypePlugins ?? []),
        // Fails to build
        rehypePrism,
        rehypeKatex,
        rehypeCodeTitles,
];
```

But after reordering the plugins, It works fine.
```js
options.rehypePlugins = [
        ...(options.rehypePlugins ?? []),
        // Work without any issue
        rehypeCodeTitles,
        rehypePrism,
        rehypeKatex,
];
```
Hope It will solve others, who are facing the same issue.

**Comment by chasemccoy** [comment] 2021-09-18 15:04
@wooorm Thanks so much for all the help with this, and for the tips on how to do that image transformation in a better way!

I'm still seeing this issue, so I took my code and simplified it down into the smallest possible example that breaks. You can check out the branch of my site here: https://github.com/chasemccoy/www/tree/mdx-bundler-bug

To reproduce the issue:

- Checkout that branch and run `yarn`
- Run `yarn start`
- Navigate in your browser to `http://localhost:3000/2021/09/test`

The code in this branch is now only running a single remark plugin, which is literally just this:

```js
const imageTransformer = (tree) => {
    // ❗ Commenting out the next 3 lines fixes the issue
    visit(tree, 'image', (node, index, parent) => {
      console.log('This breaks?')
    })

    return tree
  }

  const remarkPlugins = [() => imageTransformer]

  const { frontmatter, code } = await bundleMDX(indexFile.content, {
    files,
    xdmOptions(options) {
      options.remarkPlugins = [
        ...(options.remarkPlugins ?? []),
        ...remarkPlugins,
      ]

      return options
    },
    esbuildOptions(options) {
      options.loader = {
        ...options.loader,
        '.js': 'jsx',
      }
      return options
    },
  })
```

**Comment by chasemccoy** [comment] 2021-09-18 16:33
I was also able to confirm that getting rid of the frontmatter of the post doesn't fix the issue:

<img width="1048" alt="Screen Shot 2021-09-18 at 11 32 51 AM" src="https://user-images.githubusercontent.com/8663074/133895825-cf6ddc3e-e301-4185-b159-ec84350413b7.png">

**Comment by chasemccoy** [comment] 2021-09-18 16:47
@wooorm 🤦‍♂️ I figured it out. I forgot to change to named exports for my unified dependencies:

I had this:

```js
import visit from 'unist-util-visit'
import toc from 'mdast-util-toc'
import toHast from 'mdast-util-to-hast'
import toHtml from 'hast-util-to-html'
```

I needed this:

```js
import {visit} from 'unist-util-visit'
import {toc} from 'mdast-util-toc'
import {toHast} from 'mdast-util-to-hast'
import {toHtml} from 'hast-util-to-html'
```

Such a small detail that I completely overlooked it. Thank you again for your help, your patience, and for all the awesome work you do!

**Comment by wooorm** [comment] 2021-09-19 07:46
Glad it works for y’all!

I don‘t understand why esbuild is involved in these error messages, though my hunch is that Next silently ignores the import errors, resulting in errors in esbuild?

If I run one of my above examples (https://github.com/kentcdodds/mdx-bundler/issues/93#issuecomment-922237007 or https://github.com/kentcdodds/mdx-bundler/issues/93#issuecomment-922240995), but mess an import up, I get an early error from Node:

```
file:///Users/tilde/Projects/oss/example/example.js:8
import visit from 'unist-util-visit'
       ^^^^^
SyntaxError: The requested module 'unist-util-visit' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

**Comment by chasemccoy** [comment] 2021-09-19 15:22
Yeah, this error getting swallowed up somewhere made it really hard to debug this. But anyway, I think we can close this issue now!

**Closed** 2021-09-20 03:16 UTC
