### ISSUE TITLE
Does this support co-locating images from the same folder as the blog?

### ISSUE THREAD

**Issue by deadcoder0904** [kentcdodds/mdx-bundler#26] opened 2021-04-21 01:19 UTC
I loved the `next-mdx-remote` API but I wasn't able to keep my images co-located as my blog posts.

See this for more info → https://stackoverflow.com/questions/63957018/how-to-use-images-in-a-mdx-file-outside-of-public-folder-while-using-next

Does `mdx-bundler` support it?

**Comment by Arcath** [comment] 2021-04-21 09:30
This is an intresting idea. I had moved all my images out of co-location when using `next-mdx-remote` as I saw that as the only solution.

`esbuild` can handle images but `mdx-bundler` is expecting its `files` to be strings so it wont bundle them. Even if it did I don't think inlining images as base64 is the solution I'd be happy with, the aim is to keep the data fetched on load as small as possible and this removes the option for browser caching to load the image.

Leave this with me. I have an idea for a remark plugin that could handle this, I'll give it a go on my site and let you know.

**Comment by deadcoder0904** [comment] 2021-04-21 09:59
Thank you, Adam. I agree base64 for lots of images just makes the HTML huge, not something I'm happy with. I'll be looking forward to it :)

**Comment by Arcath** [comment] 2021-04-22 12:26
I've thrown together this: https://github.com/Arcath/remark-plugin-colocate-images

It does exactly what it says on the tin and copies images from the source directory of each post to a location in your public directory.

You do have to exclude the now _generated_ directory from git so it doesn't get comitted and its a bit dumb at the moment around collisions. 

I've been supplying a folder per post to copy to similar to what I manually did when I moved to `next-mdx-remote`.

Because its a remark plugin it will work with `next-mdx-remote` aswell as `mdx-bundler`.

```ts
const {code} = await bundleMDX(source, {
    files,
    xdmOptions: (input, options) => {
      options.remarkPlugins = [
        ...(options.remarkPlugins ?? []),
        colocateImagesPlugin({
          diskRoot: '/path/to/post/directory', // Where on the disk is the posts content, e.g. index.md and image.jpg
          diskReplace: '/path/to/public/directory/img', // Where on the disk should files be copied to
          urlReplace: '/img/', // Needs the trailing slash, replaces `./` in the image path.
        })
      ]
      
      return options
    }
  })
```

A post as well as an example in my sites source code is coming. If you ahve any suggestions let me know. I'm already looking at it thinking _"if its copying images can it make webp versions"_ and other similar ideas.

**Comment by deadcoder0904** [comment] 2021-04-22 12:50
Lovely! Any downsides to this approach? Looks really good but don't want to migrate back if some downsides that I can't compromise.

Ideally, I have 2 paths: `posts/` & `tutorials` so I don't think right now it works with more than 1 path.

> If you have any suggestions let me know. I'm already looking at it thinking "if its copying images can it make webp versions" and other similar ideas.

That would be wonderful. Basically, something like Gatsby Images.

**Comment by Arcath** [comment] 2021-04-22 12:57
I'm using quite a few folders. I pass the images target directory with my mdx source for the post/project/page etc... so its using a different directory for each _content type_ and then a sub folder for each slug. Seems to be working pretty well on my dev site here. I'll update here when I publish the site using it.

**Comment by kentcdodds** [comment] 2021-04-22 13:22
Wonder whether it would be reasonable to make that plugin work without saving the source images to disk. In my case the images are in a remote github repo and I download all the files, but just store them in memory rather than saving them to disk. I think it'd work better for my use case if I could just pass their string-form with the filepath (similar to the `files` for the mdx-bundler config) and the plugin could use that rather than reading from disk.

**Comment by Arcath** [comment] 2021-04-22 13:35
@kentcdodds I though the same originally but wasn't sure on the best approach as a remark plugin. To "sideload" it into the bundle by Next.JS felt like a very implementation specific problem.

I am thinking a `handleImage` option might be the best here that way the user can handle it how every they want and return the path to put in the image tag. With the default being its file copy approach.

**Comment by kentcdodds** [comment] 2021-04-22 16:03
I'm not sure I understand what you're suggesting, but I'll trust you know what you're doing :)

Also, some of the use cases for this may be handled by #28 if that happens.

**Comment by Arcath** [comment] 2021-04-23 10:17
On the subject of #29 it wont help with images specified in the markdown as esbuild doesn't see them.

**Comment by Arcath** [comment] 2021-04-26 13:08
So file copies are working great on my site and I'm now looking at getting them to bundle.

Using `handleImage` I've got this:

```ts
colocateImagesPlugin({
  handleImage: async (src) => {
    const imgSrc = import(src)

    return imgSrc
  }
})
```

which is currently throwing an error from `inMemory` because I'm not rolling with #29 merged on my site. I do find it intresting that its esbuild and not next.js handling this. Does bring me some hope that this can be solved in `mdx-bundler`.

Ultimatley now I just need to tell esbuild what to do with images.

**Comment by Arcath** [comment] 2021-04-27 11:17
Keeping going with this theme I've found [remark-mdx-images](https://www.npmjs.com/package/remark-mdx-images) which swaps out image paths for imports. This then triggers esbuild to bundle the images.

I've added a test to show that it works as intended in #29 which is great however its bundling as inline base64. I need to have a play with the settings once that PR is merged but its looking pretty promising.

**Comment by karlhorky** [comment] 2021-04-29 08:28
@Arcath this looks really cool! Now that this is merged, is there a demo / example that achieves the original functionality requested by @deadcoder0904 in this issue? Eg. I can't tell from a quick look whether `colocateImagesPlugin` and `handleImage` are real APIs that can be used or whether that's just some way that it could possibly work, if they did exist :) 

Would be great to get this example added to the readme to make it easy for those who want to colocate images like suggested in this issue.

Or maybe #29 wasn't the whole story to closing this issue?

**Comment by Arcath** [comment] 2021-04-29 08:49
@karlhorky #29 was a start.

I have it working on my site using the `dataurl` loader currently which as discussed with @deadcoder0904 isnt the ideal solution but its working for now. See [my prepareMDX function](https://github.com/Arcath/arcath.net-next/blob/b11d432d304c3e1a483aa7d58681c79ce2cf2761/lib/functions/prepare-mdx.ts).

I've just opened PR #34 which allows use of the `file` loader and its great! Images get copied to the supplied location on disk ready for what ever webserver you are using to serve them.

**Comment by karlhorky** [comment] 2021-04-29 08:53
Ah, amazing! Maybe this issue should be reopened then? Since there is not a clean, complete solution to this yet? And then close it when #34 and the documentation for it lands?

**Comment by Arcath** [comment] 2021-04-29 08:55
Re-opening until we have `file` loader working and docs for it.

**Closed** 2021-04-29 13:21 UTC
Labels: released

**Comment by karlhorky** [comment] 2021-04-29 13:25
Wow, super fast 🐎💨  great job @Arcath and @kentcdodds !

**Comment by deadcoder0904** [comment] 2021-04-29 14:44
Nice one @Arcath

I am assuming this copies images from my blog post folder to `public/` folder & renames it if name collision happens?

**Comment by Arcath** [comment] 2021-04-29 15:22
> 
> 
> Nice one @Arcath
> 
> I am assuming this copies images from my blog post folder to `public/` folder & renames it if name collision happens?

It over-writes as far as I am aware, each call to `bundleMDX` is unaware of wha the previous runs have returned.

Personally I set the cwd, outdir, and public path per post so there is no chance of collisions with other _builds_.

I have post in the works about it that should be going out this evening.

**Comment by karlhorky** [comment] 2021-04-30 07:58
> I have post in the works about it that should be going out this evening.

Cool, can you link it here too?

**Comment by Arcath** [comment] 2021-04-30 08:30
@karlhorky of course!

I've written it up here: https://www.arcath.net/2021/04/images-with-mdx-bundler

**Comment by jsardid** [comment] 2021-12-28 22:20
Thanks @Arcath, your solution is already working for me, but I'd like to ask something.

Since this approach copies the co-located images to "/public", am I right to assume that these files are now duplicated(co-located with the MDX and also in "/public")? I'm thinking about gitignoring the ones in "public" (it feels like they shouldn't be there before-build), but I wanted to make sure I'm getting things right first.
